### ISSUE TITLE
What is everybody going to be working on?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/OGCAPI-EDR-Sprint2#1]
Post a comment letting us know what you are going to be working on.

**Comment by chris-little** [comment]
As my coding and scripting days are long past and I am now a 'suit', I will be gathering issues, requirements, outcomes, etc., and publishing on GitHub. And influencing.
(If I was there in person, I would probably be running around distributing coffee, pizza and beer)

**Comment by dblodgett-usgs** [comment]
My hope is to plan and perhaps start an EDR API server wrapping USGS streamflow web services. Will follow the mock up here. https://github.com/opengeospatial/Environmental-Data-Retrieval-API/wiki/Monitoring-network-mockup

**Comment by jkreft-usgs** [comment]
I (or potentially others as interested) would be interested in building out a client based on one of the openAPI code generation tools.

**Comment by chris-little** [comment]
@PeterTrevelyan will work on examples, potentially to go the spec annex or a Best Practice document

**Comment by chris-little** [comment]
@iandruska-ibl will be focussing on metadata exposure from IBL's server, using C++. IBL's server has a wide range of data types

**Comment by chris-little** [comment]
@m-burgoyne will probably work on:
1.  a VisualCode++ extension to easily test and extend schemas 

2. try to implement API on the fisheries use case and its OGC standard datastores

**Comment by chris-little** [comment]
@ShaneMill1 will probably build some test scripts, perhaps using SmartBear, focussing on valid queries to keep a narrow scope.

**Comment by iandruska-ibl** [comment]
In general, I would like to test interoperability on metadata level.

In our software, we have this GUI dialog for browsing NWP datasets:
![Screenshot from 2020-11-05 16-23-38](https://user-images.githubusercontent.com/63037383/98260312-78098a00-1f83-11eb-9d1c-bd20dd8d9d71.png)

My plan is to implement an EDR backend into this dialog and to test it against all implementations. Goal is to identify missing/deficient information, inconsistencies or any issues with metadata that might pose unnecessary obstacles to implementers.

**Comment by ShaneMill1** [comment]
> @ShaneMill1 will probably build some test scripts, perhaps using SmartBear, focussing on valid queries to keep a narrow scope.

In addition to test scripts, I will be in coordination with @m-burgoyne regarding implementations

**Comment by boyi-shangguan** [comment]
WHU plans to develop a use case client demo of "Flood Disaster Decision Support System" to use EDR API to gather data, instead of using a WPS workflow to extract data of interesting area from WCS or WFS server originally.
![1](https://user-images.githubusercontent.com/14161208/98316152-d16dc980-2014-11eb-9708-fe0acaa275fe.png)
![2](https://user-images.githubusercontent.com/14161208/98316188-e0547c00-2014-11eb-8768-8ad8fa43df33.png)

**Comment by StephanSiemen** [comment]
Anyone needs some helping hands? I am otherwise play with [pygeoapi](https://github.com/geopython/pygeoapi) and see how it can be possibly be the frontend at ECMWF for an EDR interface to our data. @tomkralidis is there anything you need help with in pygeoapi for supporting EDR? Any area need more testing?

**Comment by NazihFino** [comment]
my plan is to test ArcGIS server enterprise ( AWS cloud)

**Comment by ludona7** [comment]
Hi, as a newcomer I just want to play around with the API from the client side. I noticed 2 of the demos looked almost identical in terms of styling, so thought they may have used a common base for the client UI.  I saw the leaflet plugin (https://github.com/Reading-eScience-Centre/leaflet-coverage) but I'm curious to know if a 'full' generic client/UI is available anywhere to use as a starting point?

**Comment by PeterTrevelyan** [comment]
Hi  Nazih,
Do you have an ESRI image server with data already loaded?
Pete T

**Comment by tomkralidis** [comment]
As time permits, I'll be looking into metadata models for search based on OGC API - Records as well as try to cover any pygeoapi EDR integration.

**Comment by NazihFino** [comment]
@PeterTrevelyan 

no, not the image server.

**Comment by PeterTrevelyan** [comment]
I  am having problems s with the internet here. Will let you know as soon as it returns to normal. Can I have your email address so I can send you an invite.
Pete

**Comment by ethanrd** [comment]
I’m using this sprint as a time to catch up on the details of the EDR API and start mapping it to the THREDDS framework (conceptually, not coding yet). We will be working on implementing basic EDR API support in the THREDDS Data Server in the next 6-12 months, starting with support for the point query.

**Comment by chris-little** [comment]
> 
> 
> Hi, as a newcomer I just want to play around with the API from the client side. I noticed 2 of the demos looked almost identical in terms of styling, so thought they may have used a common base for the client UI. I saw the leaflet plugin (https://github.com/Reading-eScience-Centre/leaflet-coverage) but I'm curious to know if a 'full' generic client/UI is available anywhere to use as a starting point?

@ludona7  A 'full' generic client is actually a browser with a URL input box! And a JSON stylesheet. 
Some are using pyegeoapi and leaflet. One of the driving use cases was to get away from people having to mess around with GeoServer, GDAL etc. The intellikgence really is in the server exposing the correct query responses. Does that make sense?

**Comment by chris-little** [comment]
> 
> 
> I’m using this sprint as a time to catch up on the details of the EDR API and start mapping it to the THREDDS framework (conceptually, not coding yet). We will be working on implementing basic EDR API support in the THREDDS Data Server in the next 6-12 months, starting with support for the point query.

@ethanrd Please talk to @dblodgett-usgs as he seems to have that clear. I think the THREDDS perspective is that a datastore/Collection/Geospatial Data with an EDR API in front is a distribution. Good to hear we are in your plans!

**Comment by ethanrd** [comment]
@chris-little - Thanks. Yes, I've talked with @dblodgett-usgs about this some, will definitely talk more.

**Comment by paul-breen** [comment]
> @ludona7 A 'full' generic client is actually a browser with a URL input box! And a JSON stylesheet.
> Some are using pyegeoapi and leaflet. One of the driving use cases was to get away from people having to mess around with GeoServer, GDAL etc. The intellikgence really is in the server exposing the correct query responses. Does that make sense?

Hi @chris-little. I'm struggling to understand that, I'm afraid!  If we wanted to run the same UI that you used in your demo, how would we go about it?  Is there an online instance of that UI we can access, or can we run it locally on our own laptops?  If the latter, what do we need to install and from where?

**Comment by chris-little** [comment]
> 
> 
> > @ludona7 A 'full' generic client is actually a browser with a URL input box! And a JSON stylesheet.
> > Some are using pyegeoapi and leaflet. One of the driving use cases was to get away from people having to mess around with GeoServer, GDAL etc. The intellikgence really is in the server exposing the correct query responses. Does that make sense?
> 
> Hi @chris-little. I'm struggling to understand that, I'm afraid! If we wanted to run the same UI that you used in your demo, how would we go about it? Is there an online instance of that UI we can access, or can we run it locally on our own laptops? If the latter, what do we need to install and from where?

@paul-breen Issue/Task17 by @jkreft-usgs is one approach to clients. @m-burgoyne can give you some pointers to the apporach that you outlined.

**Comment by chris-little** [comment]
All the tasks identified above have been copied into separate Issues (#16 to #26). Please continue discussions there.
