### ISSUE TITLE
EDR-API Plug-in for pygeoapi

### ISSUE THREAD

**Issue by ShaneMill1** [opengeospatial/OGCAPI-EDR-Sprint2#12]
https://pygeoapi.io/

Tom Kralidis @tomkralidis 13:18
@ShaneMill1 thanks. For pygeoapi, we would basically need a pygeoapi EDR plugin that is able to do the following to a resource:

list parameters
list instances
query per the query types
The rest would be part of the core pygeoapi machinery.

**Comment by tomkralidis** [comment]
Here is a first pass skeleton of pygeoapi EDR API : https://github.com/tomkralidis/pygeoapi/tree/edr-api, which is a shim sitting on top of pygeoapi’s xarray/zarr support using the pygeoapi plugin architecture.

From here, one would, in `pygeoapi/provider/edr.py`, transform the EDR parameters into (in this case) xarray provider parameters and then send to xarray proper to return the extracted data in native data format or CoverageJSON.

**Comment by ShaneMill1** [comment]
@tomkralidis I cloned your repository last night but have not been able to look at things quite yet. definitely will (likely post sprint)
