### ISSUE TITLE
Mandatory Conformance Class URI is missing from the example in Section 8.2.3.

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/OGCAPI-EDR-Sprint2#14]
The Conformance Class URI (http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/core) specified in Requirement 2 Section A.2 is missing from the example in Section 8.2.3.

The example in Section 8.2.3 looks like this.

```json
 {
    "conformsTo": [
"http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core", 
"http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/collections", 
"http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/oas3",
 "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/html", 
"http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/geojson", 
"http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/core"
] }
 
```

Section A.2 states this.

![Screenshot 2020-11-09 at 21 37 28](https://user-images.githubusercontent.com/18121038/98599406-d1e7b800-22d3-11eb-9091-4bf08830f578.png)

So this URI is missing: http://www.opengis.net/spec/ogcapi-edr-1/1.0/conf/core

**Comment by ghobona** [comment]
One more thing. Please replace `http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/collections` with `http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections`.

See the [this page](https://github.com/opengeospatial/oapi_common/blob/master/collections/abstract_tests/ATS_class_collections.adoc) for more Information.

**Comment by ghobona** [comment]
Another thing. Please replace `http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/geojson` with `http://www.opengis.net/spec/ogcapi-common/1.0/conf/json`.

See  [this page](https://github.com/opengeospatial/oapi_common/blob/master/core/abstract_tests/ATS_class_json.adoc) for more Information.

**Comment by chris-little** [comment]
> 
> 
> Another thing. Please replace `http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/geojson` with `http://www.opengis.net/spec/ogcapi-common/1.0/conf/json`.
> 
> See [this page](https://github.com/opengeospatial/oapi_common/blob/master/core/abstract_tests/ATS_class_json.adoc) for more Information.

@ghobona Did you mean 
http://www.opengis.net/spec/ogcapi-common/1.0/conf/json
or
http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/json
?

**Comment by chris-little** [comment]
Corrections all done to Sprint2 branch. Cross checked json conformance - it is `/ogcapi-common-1/`
