### ISSUE TITLE
Task: EDR API server wrapping USGS streamflow web services

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/OGCAPI-EDR-Sprint2#16]
My hope is to plan and perhaps start an EDR API server wrapping USGS streamflow web services. Will follow the mock up here. https://github.com/opengeospatial/Environmental-Data-Retrieval-API/wiki/Monitoring-network-mockup

_Originally posted by @dblodgett-usgs in https://github.com/opengeospatial/OGCAPI-EDR-Sprint2/issues/1#issuecomment-722417774_

**Comment by ztaylor54** [comment]
@dblodgett-usgs are you working on this? I would be happy to assist.

**Comment by dblodgett-usgs** [comment]
Yep. See: https://github.com/opengeospatial/OGCAPI-EDR-Sprint2/tree/master/usgs_collection
