### ISSUE TITLE
Task: Build client based on an openAPI code generation tool

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/OGCAPI-EDR-Sprint2#17]
I (or potentially others as interested) would be interested in building out a client based on one of the openAPI code generation tools.

_Originally posted by @jkreft-usgs in https://github.com/opengeospatial/OGCAPI-EDR-Sprint2/issues/1#issuecomment-722422635_

**Comment by chris-little** [comment]
@paul-breen Have you by any chance started building an EDR API on top of your BAS SOS public server? @m-burgoyne is interested and I would hate duplication of effort.

**Comment by paul-breen** [comment]
@chris-little No I haven't.  It's definitely something that we're interested in, but if I'm honest, it's a long way off for us at the moment.

**Comment by chris-little** [comment]
@paul-breen That's what Sprints are for! ;-)

**Comment by paul-breen** [comment]
Indeed, if only we had the resources!  At the moment, we do have a RESTful API onto our SOS instance.  It's the timeseries API, developed by [52 North](https://52north.org/), who also developed the SOS implementation we use.  So in that sense, the immediate requirement for us is satisfied, but it's not the easiest API to work with, and it's essentially proprietary. I'm kind of hoping that they may develop an EDR extension for their SOS offering.
