### ISSUE TITLE
Task: Client EDR API demo of "Flood Disaster Decision Support System" instead of  WPS/WCS/WFS

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/OGCAPI-EDR-Sprint2#20]
WHU plans to develop a use case client demo of "Flood Disaster Decision Support System" to use EDR API to gather data, instead of using a WPS workflow to extract data of interesting area from WCS or WFS server originally.
![1](https://user-images.githubusercontent.com/14161208/98316152-d16dc980-2014-11eb-9708-fe0acaa275fe.png)
![2](https://user-images.githubusercontent.com/14161208/98316188-e0547c00-2014-11eb-8768-8ad8fa43df33.png)

_Originally posted by @boyi-shangguan in https://github.com/opengeospatial/OGCAPI-EDR-Sprint2/issues/1#issuecomment-722755761_

**Comment by boyi-shangguan** [comment]
We have registed related data as collections in [WHU EDR Demo](http://geos.whu.edu.cn/whu-edr-demo) server, including village, school, bridge and paddy filed locations in Hainan. These data are queried in our use case demo with edr api to provide flood affected area analysis.
![1](https://user-images.githubusercontent.com/14161208/98669439-5ac22a80-238c-11eb-8065-aad220b66802.png)

**Comment by boyi-shangguan** [comment]
We think we can use GFS data provided by NWS EDR Server to query precipitation information in Hainan, but we use Cesium instead of Leaflet in our use case demo, it cannot well display CoverageJSON layer yet.
![2](https://user-images.githubusercontent.com/14161208/98670823-4121e280-238e-11eb-9c33-eb79aa72579c.png)

**Comment by boyi-shangguan** [comment]
The link address of our temporary use case demo is: [http://geos.whu.edu.cn:8081/monitor-forecast-edr/?l=en-au](http://geos.whu.edu.cn:8081/monitor-forecast-edr/?l=en-au)
