### ISSUE TITLE
Task: Explore using pygeoapi as a EDR API to frontend ECMWF data

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/OGCAPI-EDR-Sprint2#21]
Anyone needs some helping hands? I am otherwise play with [pygeoapi](https://github.com/geopython/pygeoapi) and see how it can be possibly be the frontend at ECMWF for an EDR interface to our data. @tomkralidis is there anything you need help with in pygeoapi for supporting EDR? Any area need more testing?

_Originally posted by @StephanSiemen in https://github.com/opengeospatial/OGCAPI-EDR-Sprint2/issues/1#issuecomment-724093023_

**Comment by tomkralidis** [comment]
As per https://github.com/opengeospatial/OGCAPI-EDR-Sprint2/issues/12#issuecomment-724341192, there is now a skeleton implementation in my edr-api branch of pygeoapi, which will allow basic EDR functionality to be put forth in a pluggable manner.

**Comment by StephanSiemen** [comment]
Thanks @tomkralidis ... we have a look at it :-)

As a small exercise we try to link our ensemble meteogram service through and EDR API ... we already learned quite a bit :-)

We have a big workshop going at the moment and will join you bit later toady

**Comment by StephanSiemen** [comment]
Not much to show today, unfortunately. We started prototyping a EDR API for Ensemble meteograms. Was a bit of a learning curve for us. We also explored pygeoapi and especially latest changes for EDR. 
We booked an internal Hackathon in December to work on this and hope to have demo server by Christmas ... keep you posted
