### ISSUE TITLE
Change format negotiation parameter from 'outputformat' to 'f'

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/OGCAPI-EDR-Sprint2#8]
The spec currently states that the format negotiation should be through an `outputformat` parameter.

However, the OpenAPI Definition document states that the parameter should be `f`  .

Note that OGC API - Features uses `f`.

**Comment by ShaneMill1** [comment]
Here is the relevant issue from the SWG github repo where I believe it was agreed that we change outputFormat to f:

https://github.com/opengeospatial/Environmental-Data-Retrieval-API/issues/96

**Comment by chris-little** [comment]
Agreed that we agreed to change to f. I think the intent was to leave both as aliases. @m-burgoyne could comment further.

**Comment by m-burgoyne** [comment]
Yes the reference to `outputformat` is an error,  it should be changed to `f`

**Comment by ghobona** [comment]
@ShaneMill1 Thanks for finding the SWG resolution.
 
@chris-little Leaving both as aliases will confuse developers. I suggest removing `outputformat` and only retaining `f`.

**Comment by chris-little** [comment]
@ghobona @ShaneMill1 @m-burgoyne Changes done in PR on candidate spec. Awaiting 2nd review and will then merge
