### ISSUE TITLE
What are the link relation types that should be returned by the landing page?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/OGCAPI-EDR-Sprint2#9]
The landing page is supposed to provide a route through to the:

* API Definition
* Conformance declaration
* Collections resource

What link relation types should be used for each of the above resources?

**Comment by ghobona** [comment]
Since the EDR API makes use of the Common and [Features API](http://docs.ogc.org/is/17-069r3/17-069r3.html#core-overview), I presume the Landing page provides links to:

* the API definition (link relations `service-desc` and `service-doc`),
* the Conformance declaration (path `/conformance`, link relation `conformance`), and
* the Collections (path `/collections`, link relation `data`).

Am I right?

**Comment by m-burgoyne** [comment]
@ghobona Yes you are correct

**Comment by ghobona** [comment]
Apologies, I had not spotted that the link relation types are listed in Section 7.2
